### ISSUE TITLE
Single "Add a new challenge" Answer and Category variables reversed.

### ISSUE THREAD

**Issue by cybersheepdog** [kkneomis/kc7_scoreboard#5]
When using the single "Add a new challenge" for a game session the "Answer" field is actually the "Category" field, and the "Category" field is actually the "Answer" field.  This means that if you switch the inputs, it will display correctly but the participants will be unable to answer the question correctly.  

![kc7_scoreboard_Issue](https://user-images.githubusercontent.com/65020364/216866042-e81f0528-5d60-40a6-8775-d5f59c40617e.png)

1. I put the answer of 42 in the "Answer" field and "easy" in the "Category" field and then clicked submit.  As you can see it displays the answer where the Category should be displayed.
2. I put the answer of 42 in the "Category" field and "Easy" in the "Answer" field and then clicked submit.  As you can see it now displays Easy where the category should be.  However, when I go to answer that question with the answer of 42 it says it is incorrect.

**Comment by kkneomis** [comment]
Great catch Jeremy! I just made some major changes to the scoreboard that splits the category across multiple pages. This should hopefully take care of that bug. Try it out and let me know if it's better. This version also allows you to enable a timer on the session.

**Comment by cybersheepdog** [comment]
Thanks for the quick response, Simon @kkneomis.  I will get the fresh pull.  Also, I found the culprit in the code:

![kc7_scoreboard_Issue_culprit](https://user-images.githubusercontent.com/65020364/216874262-16c30e6b-4b2e-4c8a-8246-c61b1b9caf04.png)

It looks like line 298 of the views.py file in kc7_scoreboard/app/server/ is category = request.form['answer'] or None, but should be category = request.form['category'] or None

**Comment by cybersheepdog** [comment]
I have confirmed it is working correctly now.  Thank you.
